# Generated by Django 4.0.5 on 2022-06-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=256)),
                ('difficulty', models.TextField(max_length=256)),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('questionSetID', models.AutoField(primary_key=True, serialize=False)),
                ('setType', models.IntegerField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('QuestionPaperID', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.TextField(max_length=256)),
                ('semester', models.IntegerField()),
                ('QuestionSetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.questionset')),
            ],
        ),
    ]
