# Generated by Django 4.0.5 on 2022-06-20 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academicyearID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ExamNote',
            fields=[
                ('examnoteID', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTypeDescriptor',
            fields=[
                ('quesitiontypedescriptorID', models.AutoField(primary_key=True, serialize=False)),
                ('code_value', models.IntegerField()),
                ('short_desc', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterDescriptor',
            fields=[
                ('semesterdescriptorID', models.AutoField(primary_key=True, serialize=False)),
                ('code_value', models.IntegerField()),
                ('short_desc', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='maxmarks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='time',
            field=models.TimeField(default=datetime.time(2, 30)),
        ),
        migrations.AddField(
            model_name='questionset',
            name='compulsorymarks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='max_questions',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='min_questions',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='optionalmarks',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.AutoField(primary_key=True, serialize=False)),
                ('subjectcode', models.CharField(default='unknown', max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('academicyearID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.academicyear')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaperSet',
            fields=[
                ('questionPaperSetID', models.AutoField(primary_key=True, serialize=False)),
                ('paperSet', models.IntegerField()),
                ('questionPaperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.questionpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subjectID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.subject'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='AcademicYearID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.academicyear'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='exam_noteID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.examnote'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subjectcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.subject'),
        ),
    ]
