# Generated by Django 4.0.5 on 2022-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0002_academicyear_course_examnote_questiontypedescriptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.TextField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY'),
        ),
    ]
