# Generated by Django 4.0.5 on 2022-06-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0003_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='AcademicYearID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.academicyear'),
        ),
    ]
