# Generated by Django 4.0.5 on 2022-06-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0004_alter_questionpaper_academicyearid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subjectID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.subject'),
        ),
    ]
