# Generated by Django 4.0.5 on 2022-06-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0005_alter_question_subjectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='AcademicYearID',
            new_name='AcademicYear',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='QuestionSetID',
            new_name='QuestionSet',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='exam_noteID',
            new_name='exam_note',
        ),
        migrations.RenameField(
            model_name='questionpaperset',
            old_name='questionPaperID',
            new_name='questionPaper',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='questionID',
            new_name='question',
        ),
    ]
