# Generated by Django 4.0.5 on 2022-06-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0006_rename_academicyearid_questionpaper_academicyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='QuestionSet',
        ),
        migrations.RemoveField(
            model_name='questionpaperset',
            name='questionPaper',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='questionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.questionset'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='questionpaperset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.questionpaperset'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='questionpaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiongenerator.questionpaper'),
        ),
    ]
