# Generated by Django 4.0.5 on 2022-06-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0007_remove_questionpaper_questionset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionset',
            options={'ordering': ['questionSetID']},
        ),
        migrations.AlterField(
            model_name='question',
            name='questionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questiongenerator.questionset'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questionpaperset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionpaper', to='questiongenerator.questionpaperset'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questionpaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionset', to='questiongenerator.questionpaper'),
        ),
    ]
