# Generated by Django 4.0.5 on 2022-06-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0008_alter_questionset_options_alter_question_questionset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['QuestionPaperID']},
        ),
        migrations.AlterUniqueTogether(
            name='questionpaper',
            unique_together={('QuestionPaperID', 'subjectcode')},
        ),
    ]
