# Generated by Django 4.0.5 on 2022-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questiongenerator', '0009_alter_questionpaper_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionpaper',
            unique_together=set(),
        ),
    ]
