# Generated by Django 4.0.5 on 2022-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rawquestion',
            fields=[
                ('rawquestionID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=256)),
                ('difficulty', models.TextField(max_length=256)),
                ('unit', models.IntegerField(max_length=256)),
            ],
        ),
    ]
